### ISSUE TITLE
about the Applicable species

### ISSUE THREAD

**Issue by RuiqinZheng** [seqcode/miniMDS#12]
Hello ,Does the software applicable in plant ,such as Arabidopsis Thaliana?
Sincerely
Ruiqin Zheng

**Comment by Lila14** [comment]
Yes, the only thing that would be different would be that you have to enter
the chromosome number manually for interchromosomal analysis, because the
number is different from the human number. This can be done using the -C
option. Also double check the naming convention. For example, yeast
chromosomes often use Roman numerals, but this would need to be changed to
Arabic numerals for interchromosomal analysis.
