### ISSUE TITLE
INPUT question

### ISSUE THREAD

**Issue by Zheng19w** [seqcode/miniMDS#25]
Dear Professor: Hello, thank you for developing such a great tool, I have some questions,

①The contact maps are then available in the hic_results/matrix folder. Raw contact maps are in the raw folder and normalized contact maps in the iced folder.

python scripts/hicpro_to_bedpe.py [NAMES BED PATH] [MATRIX PATH] [OUTPUT BED PATH]
Which map to use here？ Raw contact maps or normalized contact maps

② python minimds_inter.py data/GM12878_combined 1000000 10000

How can I get information about the interaction between chromosomes, is there any code I can use, please forgive my limited programming ability, and how can I combine the information within and between chromosomes.

③ How will I use pymol to interface with miniMDS

I look forward to hearing from you and thank you again for developing such a great tool！

**Comment by Lila14** [comment]
1: normalized

2: I've added a script to run interchromosomal MDS on HiC-Pro output, because it sounds like that's what you're using. You can check their [documentation](https://github.com/nservant/HiC-Pro)

Use: 

`cd scripts`
`bash hicpro_interchromosomal.sh [BED file of the restriction fragments after digestion] [.matrix output from build_contact_maps] [resolution]`

Example:

`bash hicpro_interchromosomal.sh /data/frags.bed /data/hic.matrix 100kb`

3: I've added a script to convert structure tsv output to .xyz format, which should work with pymol. It represents all nodes as carbon atoms and ignores missing data. 

Use: 

`cd scripts`
`bash structure_to_xyz.sh [structure.tsv file]`

Example:

`bash structure_to_xyz.sh /data/hic_1_100kb_structure.tsv`

**Comment by Zheng19w** [comment]
Thank you very much for your detailed answer🤝🤝🤝



---- Replied Message ----
| From | Lila ***@***.***> |
| Date | 06/14/2023 10:56 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [seqcode/miniMDS] INPUT question (Issue #25) |

1: normalized

2: I've added a script to run interchromosomal MDS on HiC-Pro output, because it sounds like that's what you're using. You can check their documentation

Use:

cd scripts
bash hicpro_interchromosomal.sh [BED file of the restriction fragments after digestion] [.matrix output from build_contact_maps] [resolution]

Example:

bash hicpro_interchromosomal.sh /data/frags.bed /data/hic.matrix 100kb

3: I've added a script to convert structure tsv output to .xyz format, which should work with pymol. It represents all nodes as carbon atoms and ignores missing data.

Use:

cd scripts
bash structure_to_xyz.sh [structure.tsv file]

Example:

bash structure_to_xyz.sh /data/hic_1_100kb_structure.tsv

**Comment by jeff-godwin** [comment]
Hi @Lila14,

I have used the XYZ file to visualize the model with py3Dmol.
I would like to use the model on the WashU browser as well. It requires a g3d file as input which can be generated from the XYZ coordinates (https://g3d.readthedocs.io/en/latest/g3dtools.html). For that, I will have to add the chromosomal bins (Start/End) to the XYZ coordinates. 
However, I observed that not all the genomic bins at 5kb resolution in any given chromosome are not covered in the XYZ file (or the TSV structures file). Is there a way to find out where the XYZ coordinates belong in a chromosome?

Thanks,
Jeff

**Comment by Lila14** [comment]
Apologies for the late reply. The bins are missing because there are no reads from them, probably due to low mappability etc. You could linearly interpolate the missing coordinates. That will create a straight line, which can look odd, so I didn't include interpolation in my structures. Good luck in your research!

**Comment by Lila14** [comment]
@Zheng19w 

Based on an issue someone else raised, I realized there was an error in my example. The resolution should be in kb (numbers only).  I've also changed it so that inter-chromosomal resolution can be different from intra-chromosomal.

To run the code with 500-kb inter-chromosomal resolution and 100-kb intra chromosomal resolution:

`bash hicpro_interchromosomal.sh /data/frags.bed /data/hic.matrix 500 100`

I've added some example data to scripts/hicpro. Now you can run the following example:

```
cd scripts/hicpro
bash hicpro_interchromosomal.sh ~/Downloads/HiC-Pro/annotation/HindIII_resfrag_hg19_filtered.bed hic.matrix 500 100
```
