### ISSUE TITLE
Hi-C pro data interchromosomal input question

### ISSUE THREAD

**Issue by RayRay6868** [seqcode/miniMDS#29]
Dear Professor: 
Hello, thank you for developing such a great tool,due to my terrible ability of coding,I have met some questions that I can't deal with.

When I use instructions lilke that :bash  hicpro_interchromosomal.sh $bed $matrix 500kb
I just met the error of minimds_inter.py,invalid int value 500kb.Then I just thought maybe I misunderstand the input format,then I use 500000,it still can't run.

Actually,I just wanna try to use the data after hicpro to infer 3D chromosome conformations through miniMDS and simulate the 3D organizational sturcture of the genome.But when I try to use the bash interchromosomal,I can't solve that problem.Looking forward to your reply,I'm sorry to bother you.

Best wishes.

**Comment by Lila14** [comment]
Thank you for pointing this out. I've fixed the issue in the code, so now it should take resolution in kb as input (numbers only). I've also changed it so that inter-chromosomal resolution can be different from intra-chromosomal.

To run the code with 500-kb inter-chromosomal resolution and 100-kb intra chromosomal resolution: 

`bash hicpro_interchromosomal.sh $bed $matrix 500 100`

I've added some example data to scripts/hicpro. Now you can run the following example:

```
cd scripts/hicpro
bash hicpro_interchromosomal.sh ~/Downloads/HiC-Pro/annotation/HindIII_resfrag_hg19_filtered.bed hic.matrix 500 100
```
